/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package csigagui;

/**
 *
 * @author Bori
 */
public class csiga extends javax.swing.JPanel {

    /**
     * Creates new form csiga
     */
    public csiga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lblKezdoKep = new javax.swing.JLabel();
        lblFocim = new javax.swing.JLabel();
        pnlFogadas = new javax.swing.JPanel();
        labFogadasKiNyer = new javax.swing.JLabel();
        cbboxFogadasKire = new javax.swing.JComboBox<>();
        butFogadok = new javax.swing.JButton();
        tbbdKorok = new javax.swing.JTabbedPane();
        pnl1Kor = new javax.swing.JPanel();
        pnlGyorsito1 = new javax.swing.JPanel();
        rbutGyorsitoZold1 = new javax.swing.JRadioButton();
        labGyoesitotKapott1 = new javax.swing.JLabel();
        rbutGyorsitoKek1 = new javax.swing.JRadioButton();
        rbutGyorsitoPiros1 = new javax.swing.JRadioButton();
        rbutGyorsitoEgyikSem1 = new javax.swing.JRadioButton();
        pnlJelenlegiAllas1 = new javax.swing.JPanel();
        lblCsigakAllasa1 = new javax.swing.JLabel();
        labAllasKek1 = new javax.swing.JLabel();
        labAllasZold1 = new javax.swing.JLabel();
        labAllasPiros1 = new javax.swing.JLabel();
        butKovetkezoKor1 = new javax.swing.JButton();
        pnl2Kor = new javax.swing.JPanel();
        pnlGyorsito2 = new javax.swing.JPanel();
        rbutGyorsitoZold2 = new javax.swing.JRadioButton();
        labGyoesitotKapott2 = new javax.swing.JLabel();
        rbutGyorsitoKek2 = new javax.swing.JRadioButton();
        rbutGyorsitoPiros2 = new javax.swing.JRadioButton();
        rbutGyorsitoEgyikSem2 = new javax.swing.JRadioButton();
        pnlJelenlegiAllas2 = new javax.swing.JPanel();
        lblCsigakAllasa2 = new javax.swing.JLabel();
        labAllasKek2 = new javax.swing.JLabel();
        labAllasZold2 = new javax.swing.JLabel();
        labAllasPiros2 = new javax.swing.JLabel();
        butKovetkezoKor2 = new javax.swing.JButton();
        pnl3Kor = new javax.swing.JPanel();
        pnlGyorsito3 = new javax.swing.JPanel();
        rbutGyorsitoZold3 = new javax.swing.JRadioButton();
        labGyoesitotKapott3 = new javax.swing.JLabel();
        rbutGyorsitoKek3 = new javax.swing.JRadioButton();
        rbutGyorsitoPiros3 = new javax.swing.JRadioButton();
        rbutGyorsitoEgyikSem3 = new javax.swing.JRadioButton();
        pnlJelenlegiAllas3 = new javax.swing.JPanel();
        lblCsigakAllasa3 = new javax.swing.JLabel();
        labAllasKek3 = new javax.swing.JLabel();
        labAllasZold3 = new javax.swing.JLabel();
        labAllasPiros3 = new javax.swing.JLabel();
        butKovetkezoKor3 = new javax.swing.JButton();
        pnl4Kor = new javax.swing.JPanel();
        pnlGyorsito4 = new javax.swing.JPanel();
        rbutGyorsitoZold4 = new javax.swing.JRadioButton();
        labGyoesitotKapott4 = new javax.swing.JLabel();
        rbutGyorsitoKek4 = new javax.swing.JRadioButton();
        rbutGyorsitoPiros4 = new javax.swing.JRadioButton();
        rbutGyorsitoEgyikSem4 = new javax.swing.JRadioButton();
        pnlJelenlegiAllas4 = new javax.swing.JPanel();
        lblCsigakAllasa4 = new javax.swing.JLabel();
        labAllasKek4 = new javax.swing.JLabel();
        labAllasZold4 = new javax.swing.JLabel();
        labAllasPiros4 = new javax.swing.JLabel();
        butKovetkezoKor4 = new javax.swing.JButton();
        pnl5Kor = new javax.swing.JPanel();
        pnlGyorsito5 = new javax.swing.JPanel();
        rbutGyorsitoZold5 = new javax.swing.JRadioButton();
        labGyoesitotKapott5 = new javax.swing.JLabel();
        rbutGyorsitoKek5 = new javax.swing.JRadioButton();
        rbutGyorsitoPiros5 = new javax.swing.JRadioButton();
        rbutGyorsitoEgyikSem5 = new javax.swing.JRadioButton();
        pnlJelenlegiAllas5 = new javax.swing.JPanel();
        lblCsigakAllasa5 = new javax.swing.JLabel();
        labAllasKek5 = new javax.swing.JLabel();
        labAllasZold5 = new javax.swing.JLabel();
        labAllasPiros5 = new javax.swing.JLabel();
        butKovetkezoKor5 = new javax.swing.JButton();
        pnlEredmény = new javax.swing.JPanel();
        labGyoztesPedig = new javax.swing.JLabel();
        lblGyoztesCsiga = new javax.swing.JLabel();
        lblFogadasEredmenye = new javax.swing.JLabel();
        butUjJatek = new javax.swing.JButton();
        butVege = new javax.swing.JButton();

        setBorder(new javax.swing.border.MatteBorder(null));
        setMaximumSize(new java.awt.Dimension(424, 536));
        setMinimumSize(new java.awt.Dimension(424, 536));

        lblKezdoKep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/csigagui/images.jpg"))); // NOI18N
        lblKezdoKep.setText("jLabel1");

        lblFocim.setFont(new java.awt.Font("Yu Gothic Light", 1, 36)); // NOI18N
        lblFocim.setForeground(new java.awt.Color(153, 0, 0));
        lblFocim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFocim.setText("Csigafutam");
        lblFocim.setBorder(new javax.swing.border.MatteBorder(null));

        pnlFogadas.setBackground(new java.awt.Color(0, 153, 51));
        pnlFogadas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fogadás", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        labFogadasKiNyer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labFogadasKiNyer.setText("Szerinted melyik csiga fog nyerni?");

        cbboxFogadasKire.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbboxFogadasKire.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kék", "Piros", "Zöld" }));

        butFogadok.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        butFogadok.setForeground(new java.awt.Color(0, 204, 204));
        butFogadok.setText("Fogadok!");

        javax.swing.GroupLayout pnlFogadasLayout = new javax.swing.GroupLayout(pnlFogadas);
        pnlFogadas.setLayout(pnlFogadasLayout);
        pnlFogadasLayout.setHorizontalGroup(
            pnlFogadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFogadasLayout.createSequentialGroup()
                .addGroup(pnlFogadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labFogadasKiNyer)
                    .addComponent(cbboxFogadasKire, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butFogadok, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlFogadasLayout.setVerticalGroup(
            pnlFogadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFogadasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labFogadasKiNyer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFogadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbboxFogadasKire)
                    .addComponent(butFogadok, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlGyorsito1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        rbutGyorsitoZold1.setText("Zöld");
        rbutGyorsitoZold1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutGyorsitoZold1ActionPerformed(evt);
            }
        });

        labGyoesitotKapott1.setText("Gyorsítót kapott:");

        rbutGyorsitoKek1.setText("Kék");
        rbutGyorsitoKek1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutGyorsitoKek1ActionPerformed(evt);
            }
        });

        rbutGyorsitoPiros1.setText("Piros");

        rbutGyorsitoEgyikSem1.setText("Egyik sem");
        rbutGyorsitoEgyikSem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutGyorsitoEgyikSem1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGyorsito1Layout = new javax.swing.GroupLayout(pnlGyorsito1);
        pnlGyorsito1.setLayout(pnlGyorsito1Layout);
        pnlGyorsito1Layout.setHorizontalGroup(
            pnlGyorsito1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGyorsito1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGyorsito1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labGyoesitotKapott1)
                    .addGroup(pnlGyorsito1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlGyorsito1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlGyorsito1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rbutGyorsitoZold1)
                                .addGroup(pnlGyorsito1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbutGyorsitoPiros1)
                                    .addComponent(rbutGyorsitoKek1)))
                            .addGroup(pnlGyorsito1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(rbutGyorsitoEgyikSem1)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlGyorsito1Layout.setVerticalGroup(
            pnlGyorsito1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGyorsito1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labGyoesitotKapott1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbutGyorsitoKek1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbutGyorsitoPiros1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbutGyorsitoZold1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbutGyorsitoEgyikSem1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlJelenlegiAllas1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCsigakAllasa1.setText("Csigák állása:");

        labAllasKek1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labAllasKek1.setForeground(new java.awt.Color(0, 0, 102));
        labAllasKek1.setText("Kék:---@");

        labAllasZold1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labAllasZold1.setForeground(new java.awt.Color(0, 153, 51));
        labAllasZold1.setText("Zöld:-@");

        labAllasPiros1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labAllasPiros1.setForeground(new java.awt.Color(255, 0, 51));
        labAllasPiros1.setText("Piros:----@");

        javax.swing.GroupLayout pnlJelenlegiAllas1Layout = new javax.swing.GroupLayout(pnlJelenlegiAllas1);
        pnlJelenlegiAllas1.setLayout(pnlJelenlegiAllas1Layout);
        pnlJelenlegiAllas1Layout.setHorizontalGroup(
            pnlJelenlegiAllas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJelenlegiAllas1Layout.createSequentialGroup()
                .addGroup(pnlJelenlegiAllas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJelenlegiAllas1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCsigakAllasa1))
                    .addGroup(pnlJelenlegiAllas1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlJelenlegiAllas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labAllasKek1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labAllasPiros1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labAllasZold1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pnlJelenlegiAllas1Layout.setVerticalGroup(
            pnlJelenlegiAllas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJelenlegiAllas1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCsigakAllasa1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labAllasKek1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labAllasPiros1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labAllasZold1)
                .addContainerGap())
        );

        butKovetkezoKor1.setText("Következő kör!");

        javax.swing.GroupLayout pnl1KorLayout = new javax.swing.GroupLayout(pnl1Kor);
        pnl1Kor.setLayout(pnl1KorLayout);
        pnl1KorLayout.setHorizontalGroup(
            pnl1KorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1KorLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(butKovetkezoKor1)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(pnl1KorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(pnlGyorsito1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlJelenlegiAllas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        pnl1KorLayout.setVerticalGroup(
            pnl1KorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1KorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl1KorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlGyorsito1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlJelenlegiAllas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butKovetkezoKor1))
        );

        tbbdKorok.addTab("1.kör ", pnl1Kor);

        pnl2Kor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlGyorsito2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        rbutGyorsitoZold2.setText("Zöld");
        rbutGyorsitoZold2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutGyorsitoZold2ActionPerformed(evt);
            }
        });

        labGyoesitotKapott2.setText("Gyorsítót kapott:");

        rbutGyorsitoKek2.setText("Kék");
        rbutGyorsitoKek2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutGyorsitoKek2ActionPerformed(evt);
            }
        });

        rbutGyorsitoPiros2.setText("Piros");

        rbutGyorsitoEgyikSem2.setText("Egyik sem");
        rbutGyorsitoEgyikSem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutGyorsitoEgyikSem2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGyorsito2Layout = new javax.swing.GroupLayout(pnlGyorsito2);
        pnlGyorsito2.setLayout(pnlGyorsito2Layout);
        pnlGyorsito2Layout.setHorizontalGroup(
            pnlGyorsito2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGyorsito2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGyorsito2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labGyoesitotKapott2)
                    .addGroup(pnlGyorsito2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlGyorsito2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlGyorsito2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rbutGyorsitoZold2)
                                .addGroup(pnlGyorsito2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbutGyorsitoPiros2)
                                    .addComponent(rbutGyorsitoKek2)))
                            .addGroup(pnlGyorsito2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(rbutGyorsitoEgyikSem2)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pnlGyorsito2Layout.setVerticalGroup(
            pnlGyorsito2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGyorsito2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labGyoesitotKapott2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbutGyorsitoKek2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbutGyorsitoPiros2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbutGyorsitoZold2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbutGyorsitoEgyikSem2))
        );

        pnlJelenlegiAllas2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCsigakAllasa2.setText("Csigák állása:");

        labAllasKek2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labAllasKek2.setForeground(new java.awt.Color(0, 0, 102));
        labAllasKek2.setText("Kék:-----@");

        labAllasZold2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labAllasZold2.setForeground(new java.awt.Color(0, 153, 51));
        labAllasZold2.setText("Zöld:------@");

        labAllasPiros2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labAllasPiros2.setForeground(new java.awt.Color(255, 0, 51));
        labAllasPiros2.setText("Piros:----@");

        javax.swing.GroupLayout pnlJelenlegiAllas2Layout = new javax.swing.GroupLayout(pnlJelenlegiAllas2);
        pnlJelenlegiAllas2.setLayout(pnlJelenlegiAllas2Layout);
        pnlJelenlegiAllas2Layout.setHorizontalGroup(
            pnlJelenlegiAllas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJelenlegiAllas2Layout.createSequentialGroup()
                .addGroup(pnlJelenlegiAllas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJelenlegiAllas2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCsigakAllasa2))
                    .addGroup(pnlJelenlegiAllas2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlJelenlegiAllas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labAllasKek2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labAllasPiros2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labAllasZold2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pnlJelenlegiAllas2Layout.setVerticalGroup(
            pnlJelenlegiAllas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJelenlegiAllas2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCsigakAllasa2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labAllasKek2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labAllasPiros2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labAllasZold2)
                .addContainerGap())
        );

        butKovetkezoKor2.setText("Következő kör!");

        javax.swing.GroupLayout pnl2KorLayout = new javax.swing.GroupLayout(pnl2Kor);
        pnl2Kor.setLayout(pnl2KorLayout);
        pnl2KorLayout.setHorizontalGroup(
            pnl2KorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2KorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(pnlGyorsito2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl2KorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl2KorLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(butKovetkezoKor2)
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(pnl2KorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlJelenlegiAllas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        pnl2KorLayout.setVerticalGroup(
            pnl2KorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2KorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl2KorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl2KorLayout.createSequentialGroup()
                        .addComponent(pnlJelenlegiAllas2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butKovetkezoKor2))
                    .addGroup(pnl2KorLayout.createSequentialGroup()
                        .addComponent(pnlGyorsito2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        tbbdKorok.addTab("2.kör ", pnl2Kor);

        pnlGyorsito3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        rbutGyorsitoZold3.setText("Zöld");
        rbutGyorsitoZold3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutGyorsitoZold3ActionPerformed(evt);
            }
        });

        labGyoesitotKapott3.setText("Gyorsítót kapott:");

        rbutGyorsitoKek3.setText("Kék");
        rbutGyorsitoKek3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutGyorsitoKek3ActionPerformed(evt);
            }
        });

        rbutGyorsitoPiros3.setText("Piros");

        rbutGyorsitoEgyikSem3.setText("Egyik sem");
        rbutGyorsitoEgyikSem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutGyorsitoEgyikSem3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGyorsito3Layout = new javax.swing.GroupLayout(pnlGyorsito3);
        pnlGyorsito3.setLayout(pnlGyorsito3Layout);
        pnlGyorsito3Layout.setHorizontalGroup(
            pnlGyorsito3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGyorsito3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGyorsito3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labGyoesitotKapott3)
                    .addGroup(pnlGyorsito3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlGyorsito3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlGyorsito3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rbutGyorsitoZold3)
                                .addGroup(pnlGyorsito3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbutGyorsitoPiros3)
                                    .addComponent(rbutGyorsitoKek3)))
                            .addGroup(pnlGyorsito3Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(rbutGyorsitoEgyikSem3)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pnlGyorsito3Layout.setVerticalGroup(
            pnlGyorsito3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGyorsito3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labGyoesitotKapott3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbutGyorsitoKek3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbutGyorsitoPiros3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbutGyorsitoZold3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbutGyorsitoEgyikSem3))
        );

        pnlJelenlegiAllas3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCsigakAllasa3.setText("Csigák állása:");

        labAllasKek3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labAllasKek3.setForeground(new java.awt.Color(0, 0, 102));
        labAllasKek3.setText("Kék:-------@");

        labAllasZold3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labAllasZold3.setForeground(new java.awt.Color(0, 153, 51));
        labAllasZold3.setText("Zöld:---------@");

        labAllasPiros3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labAllasPiros3.setForeground(new java.awt.Color(255, 0, 51));
        labAllasPiros3.setText("Piros:----@");

        javax.swing.GroupLayout pnlJelenlegiAllas3Layout = new javax.swing.GroupLayout(pnlJelenlegiAllas3);
        pnlJelenlegiAllas3.setLayout(pnlJelenlegiAllas3Layout);
        pnlJelenlegiAllas3Layout.setHorizontalGroup(
            pnlJelenlegiAllas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJelenlegiAllas3Layout.createSequentialGroup()
                .addGroup(pnlJelenlegiAllas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJelenlegiAllas3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCsigakAllasa3))
                    .addGroup(pnlJelenlegiAllas3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnlJelenlegiAllas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labAllasKek3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labAllasPiros3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labAllasZold3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pnlJelenlegiAllas3Layout.setVerticalGroup(
            pnlJelenlegiAllas3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJelenlegiAllas3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCsigakAllasa3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labAllasKek3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labAllasPiros3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labAllasZold3)
                .addContainerGap())
        );

        butKovetkezoKor3.setText("Következő kör!");

        javax.swing.GroupLayout pnl3KorLayout = new javax.swing.GroupLayout(pnl3Kor);
        pnl3Kor.setLayout(pnl3KorLayout);
        pnl3KorLayout.setHorizontalGroup(
            pnl3KorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl3KorLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(butKovetkezoKor3)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(pnl3KorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(pnlGyorsito3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlJelenlegiAllas3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        pnl3KorLayout.setVerticalGroup(
            pnl3KorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl3KorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl3KorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlGyorsito3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlJelenlegiAllas3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(butKovetkezoKor3))
        );

        tbbdKorok.addTab("3.kör ", pnl3Kor);

        pnlGyorsito4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        rbutGyorsitoZold4.setText("Zöld");
        rbutGyorsitoZold4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutGyorsitoZold4ActionPerformed(evt);
            }
        });

        labGyoesitotKapott4.setText("Gyorsítót kapott:");

        rbutGyorsitoKek4.setText("Kék");
        rbutGyorsitoKek4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutGyorsitoKek4ActionPerformed(evt);
            }
        });

        rbutGyorsitoPiros4.setText("Piros");

        rbutGyorsitoEgyikSem4.setText("Egyik sem");
        rbutGyorsitoEgyikSem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutGyorsitoEgyikSem4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGyorsito4Layout = new javax.swing.GroupLayout(pnlGyorsito4);
        pnlGyorsito4.setLayout(pnlGyorsito4Layout);
        pnlGyorsito4Layout.setHorizontalGroup(
            pnlGyorsito4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGyorsito4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGyorsito4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labGyoesitotKapott4)
                    .addGroup(pnlGyorsito4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlGyorsito4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlGyorsito4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rbutGyorsitoZold4)
                                .addGroup(pnlGyorsito4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbutGyorsitoPiros4)
                                    .addComponent(rbutGyorsitoKek4)))
                            .addGroup(pnlGyorsito4Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(rbutGyorsitoEgyikSem4)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pnlGyorsito4Layout.setVerticalGroup(
            pnlGyorsito4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGyorsito4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labGyoesitotKapott4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbutGyorsitoKek4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbutGyorsitoPiros4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbutGyorsitoZold4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbutGyorsitoEgyikSem4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlJelenlegiAllas4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCsigakAllasa4.setText("Csigák állása:");

        labAllasKek4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labAllasKek4.setForeground(new java.awt.Color(0, 0, 102));
        labAllasKek4.setText("Kék:--------------@");

        labAllasZold4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labAllasZold4.setForeground(new java.awt.Color(0, 153, 51));
        labAllasZold4.setText("Zöld:----------@");

        labAllasPiros4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labAllasPiros4.setForeground(new java.awt.Color(255, 0, 51));
        labAllasPiros4.setText("Piros:-----------@");

        javax.swing.GroupLayout pnlJelenlegiAllas4Layout = new javax.swing.GroupLayout(pnlJelenlegiAllas4);
        pnlJelenlegiAllas4.setLayout(pnlJelenlegiAllas4Layout);
        pnlJelenlegiAllas4Layout.setHorizontalGroup(
            pnlJelenlegiAllas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labAllasZold4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlJelenlegiAllas4Layout.createSequentialGroup()
                .addGroup(pnlJelenlegiAllas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJelenlegiAllas4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCsigakAllasa4)
                        .addGap(0, 119, Short.MAX_VALUE))
                    .addComponent(labAllasPiros4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labAllasKek4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlJelenlegiAllas4Layout.setVerticalGroup(
            pnlJelenlegiAllas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJelenlegiAllas4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCsigakAllasa4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labAllasKek4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labAllasPiros4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labAllasZold4)
                .addContainerGap())
        );

        butKovetkezoKor4.setText("Következő kör!");

        javax.swing.GroupLayout pnl4KorLayout = new javax.swing.GroupLayout(pnl4Kor);
        pnl4Kor.setLayout(pnl4KorLayout);
        pnl4KorLayout.setHorizontalGroup(
            pnl4KorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl4KorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(pnlGyorsito4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl4KorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl4KorLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(butKovetkezoKor4)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(pnl4KorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlJelenlegiAllas4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pnl4KorLayout.setVerticalGroup(
            pnl4KorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl4KorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl4KorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl4KorLayout.createSequentialGroup()
                        .addComponent(pnlJelenlegiAllas4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butKovetkezoKor4))
                    .addGroup(pnl4KorLayout.createSequentialGroup()
                        .addComponent(pnlGyorsito4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        tbbdKorok.addTab("4.kör ", pnl4Kor);

        pnlGyorsito5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        rbutGyorsitoZold5.setText("Zöld");
        rbutGyorsitoZold5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutGyorsitoZold5ActionPerformed(evt);
            }
        });

        labGyoesitotKapott5.setText("Gyorsítót kapott:");

        rbutGyorsitoKek5.setText("Kék");
        rbutGyorsitoKek5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutGyorsitoKek5ActionPerformed(evt);
            }
        });

        rbutGyorsitoPiros5.setText("Piros");

        rbutGyorsitoEgyikSem5.setText("Egyik sem");
        rbutGyorsitoEgyikSem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbutGyorsitoEgyikSem5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGyorsito5Layout = new javax.swing.GroupLayout(pnlGyorsito5);
        pnlGyorsito5.setLayout(pnlGyorsito5Layout);
        pnlGyorsito5Layout.setHorizontalGroup(
            pnlGyorsito5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGyorsito5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGyorsito5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labGyoesitotKapott5)
                    .addGroup(pnlGyorsito5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlGyorsito5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlGyorsito5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rbutGyorsitoZold5)
                                .addGroup(pnlGyorsito5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbutGyorsitoPiros5)
                                    .addComponent(rbutGyorsitoKek5)))
                            .addGroup(pnlGyorsito5Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(rbutGyorsitoEgyikSem5)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pnlGyorsito5Layout.setVerticalGroup(
            pnlGyorsito5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGyorsito5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labGyoesitotKapott5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbutGyorsitoKek5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbutGyorsitoPiros5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbutGyorsitoZold5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbutGyorsitoEgyikSem5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlJelenlegiAllas5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblCsigakAllasa5.setText("Csigák állása:");

        labAllasKek5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labAllasKek5.setForeground(new java.awt.Color(0, 0, 102));
        labAllasKek5.setText("Kék:--------------@");

        labAllasZold5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labAllasZold5.setForeground(new java.awt.Color(0, 153, 51));
        labAllasZold5.setText("Zöld:----------@");

        labAllasPiros5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labAllasPiros5.setForeground(new java.awt.Color(255, 0, 51));
        labAllasPiros5.setText("Piros:--------------@");

        javax.swing.GroupLayout pnlJelenlegiAllas5Layout = new javax.swing.GroupLayout(pnlJelenlegiAllas5);
        pnlJelenlegiAllas5.setLayout(pnlJelenlegiAllas5Layout);
        pnlJelenlegiAllas5Layout.setHorizontalGroup(
            pnlJelenlegiAllas5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJelenlegiAllas5Layout.createSequentialGroup()
                .addGroup(pnlJelenlegiAllas5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJelenlegiAllas5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCsigakAllasa5))
                    .addComponent(labAllasKek5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlJelenlegiAllas5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlJelenlegiAllas5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labAllasZold5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labAllasPiros5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pnlJelenlegiAllas5Layout.setVerticalGroup(
            pnlJelenlegiAllas5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJelenlegiAllas5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCsigakAllasa5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labAllasKek5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labAllasPiros5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labAllasZold5)
                .addContainerGap())
        );

        butKovetkezoKor5.setText("Következő kör!");

        javax.swing.GroupLayout pnl5KorLayout = new javax.swing.GroupLayout(pnl5Kor);
        pnl5Kor.setLayout(pnl5KorLayout);
        pnl5KorLayout.setHorizontalGroup(
            pnl5KorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl5KorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(pnlGyorsito5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnl5KorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl5KorLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(butKovetkezoKor5)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(pnl5KorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlJelenlegiAllas5, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnl5KorLayout.setVerticalGroup(
            pnl5KorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl5KorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl5KorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl5KorLayout.createSequentialGroup()
                        .addComponent(pnlJelenlegiAllas5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butKovetkezoKor5))
                    .addGroup(pnl5KorLayout.createSequentialGroup()
                        .addComponent(pnlGyorsito5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        tbbdKorok.addTab("5.kör ", pnl5Kor);

        labGyoztesPedig.setFont(new java.awt.Font("Yu Gothic Light", 3, 24)); // NOI18N
        labGyoztesPedig.setText("A győztes pedig :");

        lblGyoztesCsiga.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGyoztesCsiga.setForeground(new java.awt.Color(153, 0, 0));
        lblGyoztesCsiga.setText("Piros Csiga");

        lblFogadasEredmenye.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        lblFogadasEredmenye.setForeground(new java.awt.Color(255, 0, 51));
        lblFogadasEredmenye.setText("A Fogadást Elveszteted!");

        butUjJatek.setForeground(new java.awt.Color(0, 153, 51));
        butUjJatek.setText("Új Játék!!!");

        butVege.setForeground(new java.awt.Color(153, 0, 0));
        butVege.setText("Vége");

        javax.swing.GroupLayout pnlEredményLayout = new javax.swing.GroupLayout(pnlEredmény);
        pnlEredmény.setLayout(pnlEredményLayout);
        pnlEredményLayout.setHorizontalGroup(
            pnlEredményLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEredményLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(butVege)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butUjJatek)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEredményLayout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(lblFogadasEredmenye)
                .addContainerGap())
            .addGroup(pnlEredményLayout.createSequentialGroup()
                .addGroup(pnlEredményLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEredményLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labGyoztesPedig, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEredményLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(lblGyoztesCsiga)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEredményLayout.setVerticalGroup(
            pnlEredményLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEredményLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labGyoztesPedig)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGyoztesCsiga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFogadasEredmenye)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEredményLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butUjJatek)
                    .addComponent(butVege))
                .addGap(17, 17, 17))
        );

        tbbdKorok.addTab("Eredmény", pnlEredmény);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(lblFocim))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tbbdKorok, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblKezdoKep, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlFogadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblKezdoKep, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFocim)
                .addGap(18, 18, 18)
                .addComponent(pnlFogadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbbdKorok, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rbutGyorsitoZold1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutGyorsitoZold1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbutGyorsitoZold1ActionPerformed

    private void rbutGyorsitoKek1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutGyorsitoKek1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbutGyorsitoKek1ActionPerformed

    private void rbutGyorsitoZold2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutGyorsitoZold2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbutGyorsitoZold2ActionPerformed

    private void rbutGyorsitoKek2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutGyorsitoKek2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbutGyorsitoKek2ActionPerformed

    private void rbutGyorsitoZold3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutGyorsitoZold3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbutGyorsitoZold3ActionPerformed

    private void rbutGyorsitoKek3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutGyorsitoKek3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbutGyorsitoKek3ActionPerformed

    private void rbutGyorsitoZold4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutGyorsitoZold4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbutGyorsitoZold4ActionPerformed

    private void rbutGyorsitoKek4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutGyorsitoKek4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbutGyorsitoKek4ActionPerformed

    private void rbutGyorsitoZold5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutGyorsitoZold5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbutGyorsitoZold5ActionPerformed

    private void rbutGyorsitoKek5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutGyorsitoKek5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbutGyorsitoKek5ActionPerformed

    private void rbutGyorsitoEgyikSem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutGyorsitoEgyikSem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbutGyorsitoEgyikSem1ActionPerformed

    private void rbutGyorsitoEgyikSem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutGyorsitoEgyikSem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbutGyorsitoEgyikSem2ActionPerformed

    private void rbutGyorsitoEgyikSem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutGyorsitoEgyikSem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbutGyorsitoEgyikSem3ActionPerformed

    private void rbutGyorsitoEgyikSem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutGyorsitoEgyikSem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbutGyorsitoEgyikSem4ActionPerformed

    private void rbutGyorsitoEgyikSem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbutGyorsitoEgyikSem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbutGyorsitoEgyikSem5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butFogadok;
    private javax.swing.JButton butKovetkezoKor1;
    private javax.swing.JButton butKovetkezoKor2;
    private javax.swing.JButton butKovetkezoKor3;
    private javax.swing.JButton butKovetkezoKor4;
    private javax.swing.JButton butKovetkezoKor5;
    private javax.swing.JButton butUjJatek;
    private javax.swing.JButton butVege;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbboxFogadasKire;
    private javax.swing.JLabel labAllasKek1;
    private javax.swing.JLabel labAllasKek2;
    private javax.swing.JLabel labAllasKek3;
    private javax.swing.JLabel labAllasKek4;
    private javax.swing.JLabel labAllasKek5;
    private javax.swing.JLabel labAllasPiros1;
    private javax.swing.JLabel labAllasPiros2;
    private javax.swing.JLabel labAllasPiros3;
    private javax.swing.JLabel labAllasPiros4;
    private javax.swing.JLabel labAllasPiros5;
    private javax.swing.JLabel labAllasZold1;
    private javax.swing.JLabel labAllasZold2;
    private javax.swing.JLabel labAllasZold3;
    private javax.swing.JLabel labAllasZold4;
    private javax.swing.JLabel labAllasZold5;
    private javax.swing.JLabel labFogadasKiNyer;
    private javax.swing.JLabel labGyoesitotKapott1;
    private javax.swing.JLabel labGyoesitotKapott2;
    private javax.swing.JLabel labGyoesitotKapott3;
    private javax.swing.JLabel labGyoesitotKapott4;
    private javax.swing.JLabel labGyoesitotKapott5;
    private javax.swing.JLabel labGyoztesPedig;
    private javax.swing.JLabel lblCsigakAllasa1;
    private javax.swing.JLabel lblCsigakAllasa2;
    private javax.swing.JLabel lblCsigakAllasa3;
    private javax.swing.JLabel lblCsigakAllasa4;
    private javax.swing.JLabel lblCsigakAllasa5;
    private javax.swing.JLabel lblFocim;
    private javax.swing.JLabel lblFogadasEredmenye;
    private javax.swing.JLabel lblGyoztesCsiga;
    private javax.swing.JLabel lblKezdoKep;
    private javax.swing.JPanel pnl1Kor;
    private javax.swing.JPanel pnl2Kor;
    private javax.swing.JPanel pnl3Kor;
    private javax.swing.JPanel pnl4Kor;
    private javax.swing.JPanel pnl5Kor;
    private javax.swing.JPanel pnlEredmény;
    private javax.swing.JPanel pnlFogadas;
    private javax.swing.JPanel pnlGyorsito1;
    private javax.swing.JPanel pnlGyorsito2;
    private javax.swing.JPanel pnlGyorsito3;
    private javax.swing.JPanel pnlGyorsito4;
    private javax.swing.JPanel pnlGyorsito5;
    private javax.swing.JPanel pnlJelenlegiAllas1;
    private javax.swing.JPanel pnlJelenlegiAllas2;
    private javax.swing.JPanel pnlJelenlegiAllas3;
    private javax.swing.JPanel pnlJelenlegiAllas4;
    private javax.swing.JPanel pnlJelenlegiAllas5;
    private javax.swing.JRadioButton rbutGyorsitoEgyikSem1;
    private javax.swing.JRadioButton rbutGyorsitoEgyikSem2;
    private javax.swing.JRadioButton rbutGyorsitoEgyikSem3;
    private javax.swing.JRadioButton rbutGyorsitoEgyikSem4;
    private javax.swing.JRadioButton rbutGyorsitoEgyikSem5;
    private javax.swing.JRadioButton rbutGyorsitoKek1;
    private javax.swing.JRadioButton rbutGyorsitoKek2;
    private javax.swing.JRadioButton rbutGyorsitoKek3;
    private javax.swing.JRadioButton rbutGyorsitoKek4;
    private javax.swing.JRadioButton rbutGyorsitoKek5;
    private javax.swing.JRadioButton rbutGyorsitoPiros1;
    private javax.swing.JRadioButton rbutGyorsitoPiros2;
    private javax.swing.JRadioButton rbutGyorsitoPiros3;
    private javax.swing.JRadioButton rbutGyorsitoPiros4;
    private javax.swing.JRadioButton rbutGyorsitoPiros5;
    private javax.swing.JRadioButton rbutGyorsitoZold1;
    private javax.swing.JRadioButton rbutGyorsitoZold2;
    private javax.swing.JRadioButton rbutGyorsitoZold3;
    private javax.swing.JRadioButton rbutGyorsitoZold4;
    private javax.swing.JRadioButton rbutGyorsitoZold5;
    private javax.swing.JTabbedPane tbbdKorok;
    // End of variables declaration//GEN-END:variables
}
